# Generated by Django 4.2.6 on 2023-11-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_cantidad_alter_carrito_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
    ]
