# Generated by Django 4.2.6 on 2023-11-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_producto_usuario'),
        ('carrito', '0003_remove_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
