# Generated by Django 4.2.6 on 2023-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_carrito_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nombre_producto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
