# Generated by Django 4.2.6 on 2023-11-13 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_carrito_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
