# Generated by Django 4.2.6 on 2023-10-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='ProductoAccesorios',
        ),
    ]
