# Generated by Django 4.2.6 on 2023-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_productoautobronceante_productobruma'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoaccesorios',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoautobronceante',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productobruma',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoaccesorios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
