# Generated by Django 4.2.6 on 2023-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_productoaccesorios_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='productos/')),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductoAccesorios',
        ),
        migrations.DeleteModel(
            name='ProductoAutobronceante',
        ),
        migrations.DeleteModel(
            name='ProductoBruma',
        ),
    ]
