# Generated by Django 4.2.6 on 2023-11-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
    ]
