# Generated by Django 4.2.6 on 2023-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_datosextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
