# Generated by Django 4.2.6 on 2023-11-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_datosextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
