# Generated by Django 4.2.6 on 2023-11-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_datosextra_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
