# Generated by Django 4.2.6 on 2023-11-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_alter_datosextra_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
