# Generated by Django 4.2.6 on 2023-11-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_delete_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
